//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityPro
    {
        public System.Guid ID { get; set; }
        public System.Guid ACTIVITYID { get; set; }
        public string PROCODE { get; set; }
        public System.Guid PROID { get; set; }
        public string BUYTIME { get; set; }
        public Nullable<int> NUM { get; set; }
        public string IMAGEPATH { get; set; }
        public string DESIMGPATH { get; set; }
    }
}
