//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BestCherryInfo
    {
        public string TITLE { get; set; }
        public string COLOR { get; set; }
        public Nullable<int> PRICE { get; set; }
        public Nullable<int> MEMBERPRICE { get; set; }
        public string IMAGEPATH { get; set; }
        public string SMALLTITLE { get; set; }
        public string CODE { get; set; }
        public string DES { get; set; }
        public System.Guid ID { get; set; }
        public Nullable<int> POLL { get; set; }
    }
}
