//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderInfo
    {
        public System.Guid ID { get; set; }
        public string CONSIGNEE { get; set; }
        public string MEMBERNUM { get; set; }
        public string MOBILE { get; set; }
        public string RECEIVER_STATE { get; set; }
        public string RECEIVER_CITY { get; set; }
        public string RECEIVER_DISTRICT { get; set; }
        public string ADDRESS { get; set; }
        public string ORDERID { get; set; }
        public string ORDERLIST { get; set; }
        public string PAYDATE { get; set; }
        public string USERNUM { get; set; }
        public Nullable<int> AMOUNT { get; set; }
        public Nullable<bool> INTERFACE { get; set; }
        public Nullable<int> ALLPRICE { get; set; }
        public Nullable<bool> INTERSUCCES { get; set; }
        public string YINLIANORDERID { get; set; }
        public Nullable<System.DateTime> SENDORDERTIME { get; set; }
        public Nullable<int> TYPE { get; set; }
        public Nullable<System.Guid> ACTIVITYID { get; set; }
        public Nullable<bool> ISHISTORY { get; set; }
        public string REMARK { get; set; }
        public string LOGISTICS { get; set; }
        public Nullable<bool> ISPRINTED { get; set; }
        public string ALLADDRESS { get; set; }
    }
}
